const model = {
    app: {
        currentPage: 'mainPage', //eller newUser, settings, mainPage, profile, ... (userLogin)
        colorMode: 'light',
    },
    UserType: ['superuser', 'adult', 'teen', 'child'],
    inputs: {
        login: {
            username: 'AleksiosMaximanus',
            password: null,
            errorMessage: null, 
        },
        register: {
            name: null,
            type: null,
            username: null,
            password: null,
            password2: null,
            email: null,
            age: null,
            errorMessage: null,
        },
        addTask: {
            name: null,
            type: [],
            ageLimit: {from: null, to: null},
            dueDate: null,
            cost: null,
            responsible: [],
        },
        profile: {
            id: null,
            name: null,
            username: null,
            email: null,
        },
        addPrize: {
            Name: null,
            ageLimit: {from: null, to: null},
            points: null,
            deadline: null,
        },
    },    
    prizes: [{
        Name: 'Blanket Fort!',
        ageLimit: {from: 5, to: 15},
        points: 30,
        deadline: null,
    }, {
        Name: 'Cinema',
        ageLimit: {from: 13, to: 20},
        points: 100,
        deadline: null,
    },
    {
        Name: 'Sjokoladebit',
        ageLimit: {from: 3, to: 20},
        points: 10,
        deadline: null,
    },
    {
        Name: '50 kroner',
        ageLimit: {from: 13, to: 20},
        points: 50,
        deadline: null,
    },
    ],
    taskTypes: [ 'once', 'dayly', 'weekly', 'monthly'],
    tasks: [
        {
            Name: 'take out garbage',
            type: ['weekly'],
            ageLimit: {from: 10, to: 20},
            dueDate: 4,
            cost: 10,
            responsible: [1789, 4521],
            done: false,
        },
        {
            Name: 'lag middag',
            type: ['weekly'],
            ageLimit: {from: 10, to: 20},
            dueDate: 1,
            cost: 20,
            responsible: [1789, 4521],
            done: false,
        },
        {
            Name: 'gå tur med bikkja',
            type: ['weekly'],
            ageLimit: {from: 10, to: 20},
            dueDate: 4,
            cost: 15,
            responsible: [1789,4521],
            done: false,
        },
    ],

    users: [{
        id: 1789,
        type: 'adult',
        name: 'Kalle Klovn',
        password: 'abc123',
        username: 'theClown',
        age: 40,
        email: 'karl.morten.lunna@gmail.com',
        points: 13,
    }, {
        id: 4521,
        type: 'superuser',
        name: 'Aleksander Agledal',
        password: 'DwarfStarConqurer27',
        username: 'AleksiosMaximanus',
        age: 20,
        email: 'aagledal@gmail.com',
        points: 23,
    }, {
        id: 1111,
        type: 'superuser',
        name: '1',
        password: '1',
        username: '1',
        age: 1,
        email: '1',
        points: 1,
    }, {
        id: 1311,
        type: 'superuser',
        name: 'Donald Duck',
        password: 'daff',
        username: 'Donaldos',
        age: 50,
        email: 'dd@andeby.com',
        points: 150,
    }
    ],
};